spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296

logging:
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8083